// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzejjxulnkqvjkfazsnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6ZWpqeHVsbmtxdmprZmF6c25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4ODEwMjQsImV4cCI6MjA2ODQ1NzAyNH0.cCFX-kKIiZoMUbT_v7BIPgluZp_rTFdvK6Lr9IOU_fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});